name: folio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-112.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.5
  scrollable_positioned_list: ^0.3.2
  hovering: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: Barlow
      fonts:
        - asset: fonts/Barlow-Regular.otf
    - family: DMSerifDisplay
      fonts:
        - asset: fonts/DMSerifDisplay-Regular.ttf

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
#  fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700




  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
